version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: carstore-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: mysql  # escolha uma senha forte
      MYSQL_DATABASE: car-store
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:7-alpine
    container_name: carstore-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  mysql_data:
  redis_data:
